openapi: 3.0.0
info:
  title: Matrix API
  description: API для работы с матрицами
  version: 1.0.0

paths:
  /matrices:
    get:
      summary: Получить список матриц
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  matrices:
                    type: array
                    items:
                      type: object
                      properties:
                        matrix_id:
                          type: integer
                        matrix_name:
                          type: string
                        node_count:
                          type: integer
                        edge_count:
                          type: integer

  /matrix/{matrix_id}:
    get:
      summary: Получить данные конкретной матрицы
      parameters:
        - name: matrix_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: object
                properties:
                  matrix_info:
                    type: object
                    properties:
                      matrix_name:
                        type: string
                  nodes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                  edges:
                    type: array
                    items:
                      type: object
                      properties:
                        from:
                          type: integer
                        to:
                          type: integer
                        value:
                          type: number
  /calculate_score:
    post:
      summary: Расчет очков для игрока с учетом порядка выбранных вершин
      description: Рассчитывает очки игрока на основе выбранных вершин и их порядка.
      operationId: calculateScore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                selectedNodes:
                  type: object
                  additionalProperties:
                    type: integer
                  description: Словарь выбранных вершин с их порядковыми номерами.
                  example:
                    "0": 4
                    "1": 3
                    "2": 2
                matrixName:
                  type: string
                  description: Имя матрицы для расчета откликов.
                  example: "example_matrix"
      responses:
        '200':
          description: Успешный ответ с результатами расчета
          content:
            application/json:
              schema:
                type: object
                properties:
                  turn_score:
                    type: number
                    format: float
                    description: Очки за отклик выбранных вершин.
                    example: 0.2304
                  order_score:
                    type: number
                    format: float
                    description: Очки за порядок выбранных вершин.
                    example: 85.0
                  total_score:
                    type: number
                    format: float
                    description: Общий счет.
                    example: 0.2304
                  turns:
                    type: array
                    items:
                      type: object
                      properties:
                        nodes:
                          type: array
                          items:
                            type: integer
                          description: Список выбранных вершин.
                        score:
                          type: number
                          format: float
                          description: Баллы за текущий ход.
                          example: 0.2304
        '400':
          description: Некорректный запрос (отсутствуют обязательные поля или ошибки в данных).
        '404':
          description: Матрица не найдена.
        '500':
          description: Внутренняя ошибка сервера.
